spring:
  application:
    name: time-tracker

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  token:
    secret-key: ${SECRET_KEY}
    access-expiration-time: ${ACCESS_EXPIRATION_TIME}
